export { default as AboutSection } from './about'
export { default as BlogSection } from './blog'
export { default as ContactSection } from './contact'
export { default as EducationSection } from './education'
export { default as ExperienceSection } from './experience'
export { default as HeroSection } from './hero'
export { default as ProjectSection } from './project'
export { default as SkillSection } from './skill'
