type Env =
  | 'NEXT_PUBLIC_EMAILJS_SERVICE_ID'
  | 'NEXT_PUBLIC_EMAILJS_TEMPLATE_ID'
  | 'NEXT_PUBLIC_EMAILJS_PUBLIC_KEY'
  | 'NEXT_PUBLIC_RESUME_URL'
  | 'NEXT_PUBLIC_EMAIL'
  | 'NEXT_PUBLIC_PHONE'
  | 'NEXT_PUBLIC_ADDRESS'
  | 'NEXT_PUBLIC_GITHUB_USERNAME'
  | 'NEXT_PUBLIC_LINKEDIN_USERNAME'
  | 'NEXT_PUBLIC_DEV_USERNAME'
  | 'NEXT_PUBLIC_LEETCODE_ID'

export const env = (name: Env) => {
  return process.env[name] || ''
}
